version: '3.5' 

services: 
    db:
      image: postgres
      hostname: db
      restart: unless-stopped
      networks:
        - redis
      environment:
        POSTGRES_USER: kuikka
        POSTGRES_PASSWORD: koponen
        POSTGRES_DB: defadockerdb
      volumes:
        - database:/var/lib/postgresql/data
      container_name: postgres_container10
    adminer:
      image: adminer
      restart: unless-stopped
      ports:
        - 8080:8080
      networks:
        - redis
      container_name: adminer_container10
    redis:
      image: "redis:alpine"
      hostname: redis
#      restart: unless-stopped
#      expose:
#        - 6379
      ports:
        - 6379:6379
      networks:
        - redis     
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - redisdata:/data
        - /home/paavo/defa/defa_docker_hw/part2.10/redis.conf:/usr/local/etc/redis/redis.conf
      container_name: redis_container10
    backend:
      image: vaapo/backend-example-docker
      hostname: backend
      build:
        context: ./backend-example-docker
        dockerfile: Dockerfile
      environment: 
        - FRONT_URL=front_url.colasloth.com
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=kuikka
        - DB_PASSWORD=koponen
        - DB_NAME=defadockerdb
        # defaults to DB_USERNAME if not set.
        - DB_HOST=db 
        #<hostname>` defaults to "localhost" if not set.
      #ports: 
      #  - 8000:8000
      expose: 
        - 8000
      depends_on:
        - redis
        - db
      networks:
        - redis
        - proxybacknw
      container_name: backend-example-docker10
    frontend:
      image: vaapo/frontend-example-docker  
      build:
        context: ./frontend-example-docker
        dockerfile: Dockerfile
      environment:
        - API_URL=http://localhost:8000
      expose:
        - 5000
#      ports: 
#        - 5000:5000
      depends_on: 
        - backend
      networks:
        - proxyfrontnw
        - proxybacknw
      container_name: frontend-example-docker10
    proxy: 
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - /var/run/docker.sock:/tmp/docker.sock:ro 
      ports:
        - 80:80
      depends_on:
        - backend
        - frontend
      networks:
        - proxyfrontnw
        - proxybacknw
networks:
  redis:
    driver: bridge
  proxyfrontnw:
      driver: bridge
  proxybacknw:
      driver: bridge
volumes:
  database:
  redisdata: