version: '3.5' 

services: 
   first_volume_exercise:
      image: devopsdockeruh/first_volume_exercise
      build: . 
      volumes:
        - type: bind
          source: ./logs.txt
          target: /usr/app/logs.txt
      container_name: first_volume_exercise
      
      